# aste
# 36
sh repeat_non_bert.sh 3 36-ASMOTEDataRest14-0,36-ASMOTEDataRest14-1,36-ASMOTEDataRest14-2,36-ASMOTEDataRest14-3,36-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.36-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 36-ASMOTEDataLapt14-0,36-ASMOTEDataLapt14-1,36-ASMOTEDataLapt14-2,36-ASMOTEDataLapt14-3,36-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.36-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 36-ASMOTEDataRest15-0,36-ASMOTEDataRest15-1,36-ASMOTEDataRest15-2,36-ASMOTEDataRest15-3,36-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.36-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 36-ASMOTEDataRest16-0,36-ASMOTEDataRest16-1,36-ASMOTEDataRest16-2,36-ASMOTEDataRest16-3,36-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.36-ASMOTEDataRest16-0.log 2>&1 &

# 37
sh repeat_non_bert.sh 3 37-ASMOTEDataRest14-0,37-ASMOTEDataRest14-1,37-ASMOTEDataRest14-2,37-ASMOTEDataRest14-3,37-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.37-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 37-ASMOTEDataLapt14-0,37-ASMOTEDataLapt14-1,37-ASMOTEDataLapt14-2,37-ASMOTEDataLapt14-3,37-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.37-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 37-ASMOTEDataRest15-0,37-ASMOTEDataRest15-1,37-ASMOTEDataRest15-2,37-ASMOTEDataRest15-3,37-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.37-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 37-ASMOTEDataRest16-0,37-ASMOTEDataRest16-1,37-ASMOTEDataRest16-2,37-ASMOTEDataRest16-3,37-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common --model_name AsteTermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common/model_name_NerLstm-include_conflict_True.0-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.37-ASMOTEDataRest16-0.log 2>&1 &

# 4
sh repeat_non_bert.sh 0 4-ASMOTEDataRest14-0,4-ASMOTEDataRest14-1,4-ASMOTEDataRest14-2,4-ASMOTEDataRest14-3,4-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.4-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 4-ASMOTEDataLapt14-0,4-ASMOTEDataLapt14-1,4-ASMOTEDataLapt14-2,4-ASMOTEDataLapt14-3,4-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.4-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 4-ASMOTEDataRest15-0,4-ASMOTEDataRest15-1,4-ASMOTEDataRest15-2,4-ASMOTEDataRest15-3,4-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.4-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 2 4-ASMOTEDataRest16-0,4-ASMOTEDataRest16-1,4-ASMOTEDataRest16-2,4-ASMOTEDataRest16-3,4-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.4-ASMOTEDataRest16-0.log 2>&1 &

# 39
sh repeat_non_bert.sh 3 39-ASMOTEDataRest14-0,39-ASMOTEDataRest14-1,39-ASMOTEDataRest14-2,39-ASMOTEDataRest14-3,39-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.39-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 39-ASMOTEDataLapt14-0,39-ASMOTEDataLapt14-1,39-ASMOTEDataLapt14-2,39-ASMOTEDataLapt14-3,39-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.39-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 39-ASMOTEDataRest15-0,39-ASMOTEDataRest15-1,39-ASMOTEDataRest15-2,39-ASMOTEDataRest15-3,39-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.39-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 39-ASMOTEDataRest16-0,39-ASMOTEDataRest16-1,39-ASMOTEDataRest16-2,39-ASMOTEDataRest16-3,39-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_True.1-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.39-ASMOTEDataRest16-0.log 2>&1 &

# 10
sh repeat_non_bert.sh 3 10-ASMOTEDataRest14-0,10-ASMOTEDataRest14-1,10-ASMOTEDataRest14-2,10-ASMOTEDataRest14-3,10-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.10-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASMOTEDataLapt14-0,10-ASMOTEDataLapt14-1,10-ASMOTEDataLapt14-2,10-ASMOTEDataLapt14-3,10-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.10-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASMOTEDataRest15-0,10-ASMOTEDataRest15-1,10-ASMOTEDataRest15-2,10-ASMOTEDataRest15-3,10-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.10-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASMOTEDataRest16-0,10-ASMOTEDataRest16-1,10-ASMOTEDataRest16-2,10-ASMOTEDataRest16-3,10-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit False --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.10-ASMOTEDataRest16-0.log 2>&1 &

# 41
sh repeat_non_bert.sh 3 41-ASMOTEDataRest14-0,41-ASMOTEDataRest14-1,41-ASMOTEDataRest14-2,41-ASMOTEDataRest14-3,41-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.41-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 41-ASMOTEDataLapt14-0,41-ASMOTEDataLapt14-1,41-ASMOTEDataLapt14-2,41-ASMOTEDataLapt14-3,41-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.41-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 41-ASMOTEDataRest15-0,41-ASMOTEDataRest15-1,41-ASMOTEDataRest15-2,41-ASMOTEDataRest15-3,41-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1  --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --include_conflict True > aste.41-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 41-ASMOTEDataRest16-0,41-ASMOTEDataRest16-1,41-ASMOTEDataRest16-2,41-ASMOTEDataRest16-3,41-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/aste_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name AsteTermBert --train True --evaluate True --predict False --crf False --position False --same_special_token False --aspect_term_aware True --lstm_layer_num_of_sentiment_specific 0 --sequence_label_attention True --softmax_after_opinion_logit True --validation_metric +opinion_sentiment_f1   --atsa_loss_weight 1 --towe_loss_weight 1 --towe_warmup True --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_True.4-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txtt --include_conflict True > aste.41-ASMOTEDataRest16-0.log 2>&1 &

