# ate
# 0
sh repeat_non_bert.sh 0 0-ASMOTEDataRest14-0,0-ASMOTEDataRest14-1,0-ASMOTEDataRest14-2,0-ASMOTEDataRest14-3,0-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataLapt14-0,0-ASMOTEDataLapt14-1,0-ASMOTEDataLapt14-2,0-ASMOTEDataLapt14-3,0-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataRest15-0,0-ASMOTEDataRest15-1,0-ASMOTEDataRest15-2,0-ASMOTEDataRest15-3,0-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataRest16-0,0-ASMOTEDataRest16-1,0-ASMOTEDataRest16-2,0-ASMOTEDataRest16-3,0-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common --model_name NerLstm --train True --evaluate True --predict False --predict_test True --crf False > ate.0-ASMOTEDataRest16-0.log 2>&1 &

# 1
sh repeat_non_bert.sh 1 1-ASMOTEDataRest14-0,1-ASMOTEDataRest14-1,1-ASMOTEDataRest14-2,1-ASMOTEDataRest14-3,1-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 1 1-ASMOTEDataLapt14-0,1-ASMOTEDataLapt14-1,1-ASMOTEDataLapt14-2,1-ASMOTEDataLapt14-3,1-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 1-ASMOTEDataRest15-0,1-ASMOTEDataRest15-1,1-ASMOTEDataRest15-2,1-ASMOTEDataRest15-3,1-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 2 1-ASMOTEDataRest16-0,1-ASMOTEDataRest16-1,1-ASMOTEDataRest16-2,1-ASMOTEDataRest16-3,1-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False > ate.1-ASMOTEDataRest16-0.log 2>&1 &

# 4
sh repeat_non_bert.sh 7 4-ASMOTEDataRest14-0,4-ASMOTEDataRest14-1,4-ASMOTEDataRest14-2,4-ASMOTEDataRest14-3,4-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 4-ASMOTEDataLapt14-0,4-ASMOTEDataLapt14-1,4-ASMOTEDataLapt14-2,4-ASMOTEDataLapt14-3,4-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 4-ASMOTEDataRest15-0,4-ASMOTEDataRest15-1,4-ASMOTEDataRest15-2,4-ASMOTEDataRest15-3,4-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 4-ASMOTEDataRest16-0,4-ASMOTEDataRest16-1,4-ASMOTEDataRest16-2,4-ASMOTEDataRest16-3,4-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/ate_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name NerBert --train True --evaluate True --predict False --predict_test True --crf False --fixed_bert False > ate.4-ASMOTEDataRest16-0.log 2>&1 &
