# atsa
# 3
sh repeat_non_bert.sh 3 3-ASMOTEDataRest14-0,3-ASMOTEDataRest14-1,3-ASMOTEDataRest14-2,3-ASMOTEDataRest14-3,3-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --include_conflict True > atsa.3-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 3-ASMOTEDataLapt14-0,3-ASMOTEDataLapt14-1,3-ASMOTEDataLapt14-2,3-ASMOTEDataLapt14-3,3-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --include_conflict True > atsa.3-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 2 3-ASMOTEDataRest15-0,3-ASMOTEDataRest15-1,3-ASMOTEDataRest15-2,3-ASMOTEDataRest15-3,3-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --include_conflict True > atsa.3-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 2 3-ASMOTEDataRest16-0,3-ASMOTEDataRest16-1,3-ASMOTEDataRest16-2,3-ASMOTEDataRest16-3,3-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --include_conflict True > atsa.3-ASMOTEDataRest16-0.log 2>&1 &

# 11
sh repeat_non_bert.sh 1 11-ASMOTEDataRest14-0,11-ASMOTEDataRest14-1,11-ASMOTEDataRest14-2,11-ASMOTEDataRest14-3,11-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common_single --model_name AtsaLSTM --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --same_special_token False --layer_number_of_lstm 1 --include_conflict True > atsa.11-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 1 11-ASMOTEDataLapt14-0,11-ASMOTEDataLapt14-1,11-ASMOTEDataLapt14-2,11-ASMOTEDataLapt14-3,11-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common_single --model_name AtsaLSTM --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --same_special_token False --layer_number_of_lstm 1 --include_conflict True > atsa.11-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 1 11-triplet_rest111-0,11-triplet_rest111-1,11-triplet_rest111-2,11-triplet_rest111-3,11-triplet_rest111-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common_single --model_name AtsaLSTM --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --same_special_token False --layer_number_of_lstm 1 --include_conflict True > atsa.11-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 1 11-ASMOTEDataRest16-0,11-ASMOTEDataRest16-1,11-ASMOTEDataRest16-2,11-ASMOTEDataRest16-3,11-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common_single --model_name AtsaLSTM --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --same_special_token False --layer_number_of_lstm 1 --include_conflict True > atsa.11-ASMOTEDataRest16-0.log 2>&1 &

# 13
sh repeat_non_bert.sh 0 13-ASMOTEDataRest14-0,13-ASMOTEDataRest14-1,13-ASMOTEDataRest14-2,13-ASMOTEDataRest14-3,13-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --train_bert False --include_conflict True > atsa.13-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 13-ASMOTEDataLapt14-0,13-ASMOTEDataLapt14-1,13-ASMOTEDataLapt14-2,13-ASMOTEDataLapt14-3,13-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --train_bert False --include_conflict True > atsa.13-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 13-ASMOTEDataRest15-0,13-ASMOTEDataRest15-1,13-ASMOTEDataRest15-2,13-ASMOTEDataRest15-3,13-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --train_bert False --include_conflict True > atsa.13-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 13-ASMOTEDataRest16-0,13-ASMOTEDataRest16-1,13-ASMOTEDataRest16-2,13-ASMOTEDataRest16-3,13-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/aspect_term_sentiment_analysis/atsa_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type bert_single --model_name AtsaBERT --train True --evaluate True --batch_size 32 --sample_mode single --aspect_term_aware True --term True --cls False --pair False --syntax False --same_special_token False --train_bert False --include_conflict True > atsa.13-ASMOTEDataRest16-0.log 2>&1 &
