# towe
# IOG
sh repeat_non_bert.sh 5 iog-ASMOTEDataRest14-0,iog-ASMOTEDataRest14-1,iog-ASMOTEDataRest14-2,iog-ASMOTEDataRest14-3,iog-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-ASMOTEDataLapt14-0,iog-ASMOTEDataLapt14-1,iog-ASMOTEDataLapt14-2,iog-ASMOTEDataLapt14-3,iog-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-ASMOTEDataRest15-0,iog-ASMOTEDataRest15-1,iog-ASMOTEDataRest15-2,iog-ASMOTEDataRest15-3,iog-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-ASMOTEDataRest16-0,iog-ASMOTEDataRest16-1,iog-ASMOTEDataRest16-2,iog-ASMOTEDataRest16-3,iog-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-ASMOTEDataRest16-0.log 2>&1 &


# 0
sh repeat_non_bert.sh 0 0-ASMOTEDataRest14-0,0-ASMOTEDataRest14-1,0-ASMOTEDataRest14-2,0-ASMOTEDataRest14-3,0-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataLapt14-0,0-ASMOTEDataLapt14-1,0-ASMOTEDataLapt14-2,0-ASMOTEDataLapt14-3,0-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataRest15-0,0-ASMOTEDataRest15-1,0-ASMOTEDataRest15-2,0-ASMOTEDataRest15-3,0-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-ASMOTEDataRest16-0,0-ASMOTEDataRest16-1,0-ASMOTEDataRest16-2,0-ASMOTEDataRest16-3,0-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-ASMOTEDataRest16-0.log 2>&1 &

# 2
sh repeat_non_bert.sh 2 2-ASMOTEDataRest14-0,2-ASMOTEDataRest14-1,2-ASMOTEDataRest14-2,2-ASMOTEDataRest14-3,2-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 2-ASMOTEDataLapt14-0,2-ASMOTEDataLapt14-1,2-ASMOTEDataLapt14-2,2-ASMOTEDataLapt14-3,2-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 1 2-ASMOTEDataRest15-0,2-ASMOTEDataRest15-1,2-ASMOTEDataRest15-2,2-ASMOTEDataRest15-3,2-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 1 2-ASMOTEDataRest16-0,2-ASMOTEDataRest16-1,2-ASMOTEDataRest16-2,2-ASMOTEDataRest16-3,2-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-ASMOTEDataRest16-0.log 2>&1 &

# 3
sh repeat_non_bert.sh 3 3-ASMOTEDataRest14-0,3-ASMOTEDataRest14-1,3-ASMOTEDataRest14-2,3-ASMOTEDataRest14-3,3-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 3-ASMOTEDataLapt14-0,3-ASMOTEDataLapt14-1,3-ASMOTEDataLapt14-2,3-ASMOTEDataLapt14-3,3-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 4 3-ASMOTEDataRest15-0,3-ASMOTEDataRest15-1,3-ASMOTEDataRest15-2,3-ASMOTEDataRest15-3,3-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 4 3-ASMOTEDataRest16-0,3-ASMOTEDataRest16-1,3-ASMOTEDataRest16-2,3-ASMOTEDataRest16-3,3-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-ASMOTEDataRest16-0.log 2>&1 &

# 8
sh repeat_non_bert.sh 0 8-ASMOTEDataRest14-0,8-ASMOTEDataRest14-1,8-ASMOTEDataRest14-2,8-ASMOTEDataRest14-3,8-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 8-ASMOTEDataLapt14-0,8-ASMOTEDataLapt14-1,8-ASMOTEDataLapt14-2,8-ASMOTEDataLapt14-3,8-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 1 8-ASMOTEDataRest15-0,8-ASMOTEDataRest15-1,8-ASMOTEDataRest15-2,8-ASMOTEDataRest15-3,8-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 1 8-ASMOTEDataRest16-0,8-ASMOTEDataRest16-1,8-ASMOTEDataRest16-2,8-ASMOTEDataRest16-3,8-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-ASMOTEDataRest16-0.log 2>&1 &

# 10
sh repeat_non_bert.sh 2 10-ASMOTEDataRest14-0,10-ASMOTEDataRest14-1,10-ASMOTEDataRest14-2,10-ASMOTEDataRest14-3,10-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-ASMOTEDataRest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 10-ASMOTEDataLapt14-0,10-ASMOTEDataLapt14-1,10-ASMOTEDataLapt14-2,10-ASMOTEDataLapt14-3,10-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-ASMOTEDataLapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASMOTEDataRest15-0,10-ASMOTEDataRest15-1,10-ASMOTEDataRest15-2,10-ASMOTEDataRest15-3,10-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-ASMOTEDataRest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-ASMOTEDataRest16-0,10-ASMOTEDataRest16-1,10-ASMOTEDataRest16-2,10-ASMOTEDataRest16-3,10-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-ASMOTEDataRest16-0.log 2>&1 &
