# towe
# IOG
sh repeat_non_bert.sh 5 iog-rest14-0,iog-rest14-1,iog-rest14-2,iog-rest14-3,iog-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest14 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-lapt14-0,iog-lapt14-1,iog-lapt14-2,iog-lapt14-3,iog-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset lapt14 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-rest15-0,iog-rest15-1,iog-rest15-2,iog-rest15-3,iog-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest15 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 5 iog-rest16-0,iog-rest16-1,iog-rest16-2,iog-rest16-3,iog-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest16 --data_type iog --model_name IOG --train True --evaluate True --predict False --crf False --epochs 10 --batch_size 32 --include_conflict True > towe.iog-rest16-0.log 2>&1 &


# 0
sh repeat_non_bert.sh 0 0-rest14-0,0-rest14-1,0-rest14-2,0-rest14-3,0-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest14 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-lapt14-0,0-lapt14-1,0-lapt14-2,0-lapt14-3,0-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset lapt14 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-rest15-0,0-rest15-1,0-rest15-2,0-rest15-3,0-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest15 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 0 0-rest16-0,0-rest16-1,0-rest16-2,0-rest16-3,0-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset rest16 --data_type common_conflict --model_name TermBiLSTM --train True --evaluate True --predict False --crf False --position False --same_special_token False --include_conflict True > towe.0-rest16-0.log 2>&1 &

# 2
sh repeat_non_bert.sh 2 2-rest14-0,2-rest14-1,2-rest14-2,2-rest14-3,2-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 2-lapt14-0,2-lapt14-1,2-lapt14-2,2-lapt14-3,2-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset lapt14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 1 2-rest15-0,2-rest15-1,2-rest15-2,2-rest15-3,2-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest15 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 1 2-rest16-0,2-rest16-1,2-rest16-2,2-rest16-3,2-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest16 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.2-rest16-0.log 2>&1 &

# 3
sh repeat_non_bert.sh 3 3-rest14-0,3-rest14-1,3-rest14-2,3-rest14-3,3-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 3 3-lapt14-0,3-lapt14-1,3-lapt14-2,3-lapt14-3,3-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset lapt14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 4 3-rest15-0,3-rest15-1,3-rest15-2,3-rest15-3,3-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest15 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 4 3-rest16-0,3-rest16-1,3-rest16-2,3-rest16-3,3-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest16 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --include_conflict True > towe.3-rest16-0.log 2>&1 &

# 8
sh repeat_non_bert.sh 0 8-rest14-0,8-rest14-1,8-rest14-2,8-rest14-3,8-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 0 8-lapt14-0,8-lapt14-1,8-lapt14-2,8-lapt14-3,8-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset lapt14 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 1 8-rest15-0,8-rest15-1,8-rest15-2,8-rest15-3,8-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest15 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 1 8-rest16-0,8-rest16-1,8-rest16-2,8-rest16-3,8-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest16 --data_type common_conflict_bert --model_name TermBert --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.8-rest16-0.log 2>&1 &

# 10
sh repeat_non_bert.sh 2 10-rest14-0,10-rest14-1,10-rest14-2,10-rest14-3,10-rest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-rest14-0.log 2>&1 &

sh repeat_non_bert.sh 2 10-lapt14-0,10-lapt14-1,10-lapt14-2,10-lapt14-3,10-lapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset lapt14 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-lapt14-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-rest15-0,10-rest15-1,10-rest15-2,10-rest15-3,10-rest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest15 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-rest15-0.log 2>&1 &

sh repeat_non_bert.sh 3 10-rest16-0,10-rest16-1,10-rest16-2,10-rest16-3,10-rest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset rest16 --data_type common_conflict_bert_with_second_sentence --model_name TermBertWithSecondSentence --train True --evaluate True --predict False --crf False --same_special_token False --fixed_bert False --include_conflict True > towe.10-rest16-0.log 2>&1 &
