# towe
# 0
sh repeat_non_bert.sh 0 0-ASMOTEDataRest14-0,0-ASMOTEDataRest14-1,0-ASMOTEDataRest14-2,0-ASMOTEDataRest14-3,0-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest14 --data_type common --model_name TermBiLSTM --train False --evaluate False --predict False --crf False --position False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common/model_name_NerLstm-include_conflict_False.0-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt  --add_predicted_aspect_term True

sh repeat_non_bert.sh 0 0-ASMOTEDataLapt14-0,0-ASMOTEDataLapt14-1,0-ASMOTEDataLapt14-2,0-ASMOTEDataLapt14-3,0-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataLapt14 --data_type common --model_name TermBiLSTM --train False --evaluate False --predict False --crf False --position False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common/model_name_NerLstm-include_conflict_False.0-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 0 0-ASMOTEDataRest15-0,0-ASMOTEDataRest15-1,0-ASMOTEDataRest15-2,0-ASMOTEDataRest15-3,0-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest15 --data_type common --model_name TermBiLSTM --train False --evaluate False --predict False --crf False --position False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common/model_name_NerLstm-include_conflict_False.0-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 0 0-ASMOTEDataRest16-0,0-ASMOTEDataRest16-1,0-ASMOTEDataRest16-2,0-ASMOTEDataRest16-3,0-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --current_dataset ASMOTEDataRest16 --data_type common --model_name TermBiLSTM --train False --evaluate False --predict False --crf False --position False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common/model_name_NerLstm-include_conflict_False.0-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

# 2
sh repeat_non_bert.sh 2 2-ASMOTEDataRest14-0,2-ASMOTEDataRest14-1,2-ASMOTEDataRest14-2,2-ASMOTEDataRest14-3,2-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.1-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 2 2-ASMOTEDataLapt14-0,2-ASMOTEDataLapt14-1,2-ASMOTEDataLapt14-2,2-ASMOTEDataLapt14-3,2-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.1-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 2 2-ASMOTEDataRest15-0,2-ASMOTEDataRest15-1,2-ASMOTEDataRest15-2,2-ASMOTEDataRest15-3,2-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.1-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 2 2-ASMOTEDataRest16-0,2-ASMOTEDataRest16-1,2-ASMOTEDataRest16-2,2-ASMOTEDataRest16-3,2-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.1-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True


# 8
sh repeat_non_bert.sh 0 8-ASMOTEDataRest14-0,8-ASMOTEDataRest14-1,8-ASMOTEDataRest14-2,8-ASMOTEDataRest14-3,8-ASMOTEDataRest14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest14 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest14/common_bert/model_name_NerBert-include_conflict_False.4-ASMOTEDataRest14-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 1 8-ASMOTEDataLapt14-0,8-ASMOTEDataLapt14-1,8-ASMOTEDataLapt14-2,8-ASMOTEDataLapt14-3,8-ASMOTEDataLapt14-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataLapt14 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataLapt14/common_bert/model_name_NerBert-include_conflict_False.4-ASMOTEDataLapt14-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 2 8-ASMOTEDataRest15-0,8-ASMOTEDataRest15-1,8-ASMOTEDataRest15-2,8-ASMOTEDataRest15-3,8-ASMOTEDataRest15-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest15 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest15/common_bert/model_name_NerBert-include_conflict_False.4-ASMOTEDataRest15-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True

sh repeat_non_bert.sh 3 8-ASMOTEDataRest16-0,8-ASMOTEDataRest16-1,8-ASMOTEDataRest16-2,8-ASMOTEDataRest16-3,8-ASMOTEDataRest16-4 nlp_tasks/absa/mining_opinions/sequence_labeling/towe_bootstrap.py --embedding_filepath glove.840B.300d.txt --bert_file_path bert-base-uncased.tar.gz --bert_vocab_file_path uncased_L-12_H-768_A-12/vocab.txt --current_dataset ASMOTEDataRest16 --data_type common_bert --model_name TermBert --train False --evaluate False --predict False --crf False --same_special_token False --fixed_bert False --ate_result_filepath_template absa/ate/ASMOTEDataRest16/common_bert/model_name_NerBert-include_conflict_False.4-ASMOTEDataRest16-%d/1571400646/models/result_of_predicting_test.txt --add_predicted_aspect_term True